# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
# your code here
import numpy as np


In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [25]:
# your code here

a = np.random.random((2,3)) * 1

b = np.random.random((2,3)) * 1
print("a", a)
print(np.add(a, b))




a [[0.73487101 0.47410526 0.56004553]
 [0.6178802  0.79274809 0.36183283]]
[[1.21889763 1.36868369 1.05074918]
 [1.49986651 1.39432706 0.70587082]]


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [29]:
# your code here
c = np.random.random((3,2)) * 1
print("c", c)

print(np.add(a,c))

#It can't add because the row and column are different 

c [[0.27063662 0.85639258]
 [0.31213434 0.07666849]
 [0.01864054 0.11541626]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [35]:
# your code here
d = np.transpose(c)
print("d:", d)

print(np.add(a,d))

d: [[0.27063662 0.31213434 0.01864054]
 [0.85639258 0.07666849 0.11541626]]
[[1.00550764 0.78623961 0.57868608]
 [1.47427277 0.86941658 0.47724909]]


Which combination of arrays are you able to multiply with each other? Why?

In [46]:
# your code here



g = np.multiply(a,d)
print(d)

e = np.multiply(a,b)
print(e)

f = np.multiply(a,c)
print(f)

# c has a different size 

[[0.27063662 0.31213434 0.01864054]
 [0.85639258 0.07666849 0.11541626]]
[[0.35569713 0.42412434 0.27481639]
 [0.54496188 0.47690058 0.12448424]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [65]:
# your code here

import random
random_sample = np.random.random(range(0, 10))


np.square(random_sample)

array([], shape=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), dtype=float64)

Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [7]:
# your code here
